apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: us-central1-docker.pkg.dev/ferrous-linker-489911-f0/registry-rd-dev-docker/grafana:12.4.0
        ports:
        - containerPort: 3000
