name: Terraform Dev Deploy

on: workflow_dispatch

jobs:
  terraform:
    name: Terraform Init, Plan and Apply (Dev)
    runs-on: ubuntu-latest

    permissions:
      id-token: write     # REQUIRED for Workload Identity Federation
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Authenticate to Google Cloud using Workload Identity Federation
      # These values come from: cd terraform/bootstrap && terraform output
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/917443109321/locations/global/workloadIdentityPools/pool-rd-dev-github/providers/provider-rd-dev-github
          service_account: sa-rd-dev-ghactions@playground-488307.iam.gserviceaccount.com

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # Terraform Init
      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      # Terraform Plan
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -input=false

      # Terraform Apply
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -input=false